// Hardcoded defaults — fallback when Supabase is down or field missing
// These match the current markdown content files exactly.

export const SECTION_META: Record<string, { label: string; icon: string }> = {
  hero: { label: 'Hero (nagłówek)', icon: '🎯' },
  stats: { label: 'Statystyki', icon: '📊' },
  pain: { label: 'Problem', icon: '😰' },
  benefits: { label: 'Korzyści', icon: '✅' },
  howitworks: { label: 'Jak działa', icon: '⚙️' },
  testimonials: { label: 'Opinie', icon: '💬' },
  transformation: { label: 'Transformacja', icon: '🚀' },
  pricing: { label: 'Cennik', icon: '💰' },
  faq: { label: 'FAQ', icon: '❓' },
  cta: { label: 'CTA (końcowe)', icon: '📢' },
  joinsection: { label: 'Dołącz (sekcja)', icon: '🤝' },
};

export const HOMEPAGE_DEFAULTS: Record<string, Record<string, string>> = {
  hero: {
    preheadline: 'Pracujesz z domu i nie możesz się skupić?',
    headline: 'Przestań prokrastynować w samotności. Dołącz do ludzi, którzy pracują razem — i kończą to, co zaczęli',
    description: 'Nie potrzebujesz więcej dyscypliny. Potrzebujesz body doubling — pracy w obecności innych, która naturalnie trzyma Cię w skupieniu. W MasterZone freelancerzy i soloprzedsiębiorcy codziennie pracują razem na żywo. Bez samotności, bez prokrastynacji, bez skakania po zadaniach.',
    ctaText: 'Dołącz do MasterZone',
    trialInfo: '97 PLN/miesiąc • Bez umów • Anulujesz kiedy chcesz',
    securityInfo: '🔒 Bezpieczne płatności – ten sam system co Netflix i Spotify',
  },
  stats: {
    sectionTitle: 'Społeczność, Która Naprawdę Pracuje Razem',
    stat1_number: '39',
    stat1_label: 'Freelancerów i Soloprzedsiębiorców',
    stat1_icon: '👥',
    stat2_number: '2,400+',
    stat2_label: 'Godzin Wspólnej Pracy Rocznie',
    stat2_icon: '⏱️',
    stat3_number: '92%',
    stat3_label: 'Członków Zostaje Dłużej Niż 3 Miesiące',
    stat3_icon: '🔄',
    stat4_number: '97 PLN',
    stat4_label: 'Miesięcznie — Mniej Niż Coworking',
    stat4_icon: '💰',
    footer: 'To nie kolejna grupa na Facebooku. To ludzie, którzy codziennie włączają kamerę i pracują razem.',
  },
  pain: {
    sectionTitle: 'WIEMY CO CIĘ BLOKUJE',
    headline: 'Nie brakuje Ci ambicji. Brakuje Ci ludzi obok.',
    subheadline: 'Pracujesz z domu. Sam. I to właśnie jest problem.',
    description: 'Wstajesz z planem na cały dzień. O 17:00 patrzysz — i znowu nic nie zrobiłeś.\n\nNie dlatego, że jesteś leniwy. Dlatego, że pracujesz w pustym mieszkaniu, gdzie nikt nie widzi, czy pracujesz, czy scrollujesz.\n\nOtwierasz laptopa i zamiast najważniejszego zadania — sprawdzasz maile. Potem Slacka. Potem „jeszcze tylko jedno" na YouTube.\n\nA te naprawdę ważne rzeczy? Przesuwasz na jutro. Znowu.\n\nI najgorsze? Nikt tego nie widzi. Nikt nie pyta „hej, jak Ci idzie?". Nikt nie siedzi obok.\n\nBo pracujesz sam. I ta samotność zabija Twoją produktywność.',
    painItems: 'Odkładasz najtrudniejsze zadania na \'po obiedzie\' — ale po obiedzie przychodzi kolejne \'jutro\'\nSkaczesz między 5 zadaniami naraz i żadnego nie kończysz do końca\nCałymi dniami nie rozmawiasz z nikim o pracy — bo kto ma to zrozumieć?\nPróbowałeś Pomodoro, aplikacji, blokowania stron — nic nie działa na dłużej\nCzujesz, że mógłbyś robić 2x więcej — ale coś Cię ciągle hamuje\nWeekend zaczyna się z poczuciem winy, bo znowu nie dowieźliście tego, co planowaliście',
    mainHeadline: 'To nie Twoja wina. To brak środowiska.',
    mainContent: 'Badania pokazują: **82% osób pracujących zdalnie czuje izolację**, a **78% doświadcza wypalenia**. To nie kwestia dyscypliny — to kwestia biologii.\n\nTwój mózg potrzebuje **obecności innych ludzi**, żeby się skupić. To zjawisko nazywa się **body doubling** — i działa nawet przez kamerę.\n\nDlatego w kawiarni pracujesz lepiej niż w domu. Nie magia — nauka.\n\n**MasterZone** daje Ci to codziennie — bez wychodzenia z domu:\n\n• koniec prokrastynacji — pracujesz z ludźmi, nie sam,\n• koniec samotności — otaczasz się przedsiębiorcami, którzy rozumieją,\n• koniec chaosu — planujesz tydzień raz, z jasnością.',
  },
  benefits: {
    sectionTitle: 'Dlaczego MasterZone Działa',
    sectionSubtitle: 'Body doubling + społeczność + struktura = koniec prokrastynacji',
    benefit1_title: 'Body doubling — pracujesz z innymi, skupiasz się naturalnie',
    benefit1_description: 'W kawiarni pracujesz lepiej niż w domu? To body doubling — mechanizm, w którym obecność innych reguluje Twoją uwagę. W MasterZone masz to codziennie, na żywo, przez kamerę. Bez dojazdu, bez kawy za 18 zł.',
    benefit2_title: 'Koniec samotności pracy z domu',
    benefit2_description: 'Nie musisz już pracować sam w pustym mieszkaniu. Codziennie spotykasz freelancerów i przedsiębiorców, którzy wiedzą, jak to jest — bo sami tak pracują. To nie networking. To ludzie, z którymi po prostu pracujesz.',
    benefit3_title: 'Planowanie, które faktycznie działa',
    benefit3_description: 'Raz w tygodniu planujesz z grupą. Mówisz na głos, co chcesz zrobić. A potem ktoś pyta: \'I jak, zrobiłeś?\'. Ta odpowiedzialność zmienia wszystko — bo nie chcesz powiedzieć \'nie\'.',
    benefit4_title: 'Nie potrzebujesz więcej dyscypliny',
    benefit4_description: 'Przestań się zmuszać. MasterZone to środowisko, które robi robotę za Ciebie — logujesz się, widzisz ludzi, pracujesz. Nie musisz się motywować. Wystarczy się pojawić.',
  },
  howitworks: {
    sectionTitle: 'Jak Działa MasterZone',
    subtitle: 'Trzy filary, które kończą prokrastynację: body doubling + planowanie + społeczność. Nie musisz się zmuszać — wystarczy się pojawić.',
    step1_title: 'Codzienne bloki pracy — body doubling na żywo',
    step1_description: 'Od poniedziałku do piątku — 3-4 bloki skupionej pracy na żywo. Włączasz kamerę, widzisz innych przy pracy, Twój mózg mówi: \'ok, pracujemy\'. To body doubling — ten sam mechanizm, który sprawia, że w kawiarni pracujesz lepiej niż sam w domu. 90 minut, w których robisz więcej niż normalnie w pół dnia.',
    step2_title: 'Wspólne planowanie tygodnia',
    step2_description: 'Raz w tygodniu planujesz z grupą. Mówisz na głos co zrobisz. A za tydzień ktoś pyta: \'I jak, dowieźliście?\'. Koniec z chaotycznymi poniedziałkami, koniec z planami tylko w głowie. Weekend masz naprawdę wolny.',
    step3_title: 'Społeczność, która rozumie Twoją codzienność',
    step3_description: 'Freelancerzy, soloprzedsiębiorcy, właściciele małych firm. Ludzie, którzy wiedzą jak to jest pracować sam — bo sami tak pracowali. Tu nie musisz tłumaczyć czemu \'praca z domu\' to nie \'wolne\'. Tu każdy to rozumie.',
    closingText: 'W MasterZone nie musisz się zmuszać do pracy. Wystarczy się pojawić — resztę robi środowisko.',
    infrastructure: 'Wszystko w jednym miejscu — na platformie Skool. Kalendarz, społeczność, kursy, nagrania. Logujesz się raz — i masz wszystko pod ręką.',
  },
  testimonials: {
    sectionTitle: 'Co Mówią Członkowie MasterZone',
    t1_name: 'Iza', t1_role: 'Wirtualna Asystentka',
    t1_content: 'Zamiast toczyć poranną walkę z budzikiem, dzięki Blokom Pracy Głębokiej o 7:56 zbieram się do pracy w ekspresowym tempie. Już o 8:00 działam, a o 8:55 świętuje pierwsze sukcesy! To jak poranny zastrzyk energii, który działa lepiej niż kawa – wsiadasz do pociągu produktywności i omijasz stacje prokrastynacji.',
    t2_name: 'Mikołaj Olejnik', t2_role: 'Członek MasterZone',
    t2_content: 'Ja lubię tę godzinę bo czas leci mi bardzo szybko i też pracuję szybko i sprawnie. I fajna jest też ta świadomość że inni pracują co bywa motywujące przy pracy zdalnej.',
    t3_name: 'Patrycja', t3_role: 'Członek MasterZone',
    t3_content: 'Odnośnie pracy głębokiej: myślę, że warto spróbować, bo sam fakt, że jesteś \'na wizji\' mobilizuje, jak również dzielenie się później z uczestnikami, czy udało się zrealizować założony cel. Dodatkowo na mnie osobiście dobrze wpływa świadomość, że to tylko godzina, więc trzeba być szybkim i wydajnym.',
    t4_name: 'Patryk Tokarz', t4_role: 'Aplikacja',
    t4_content: 'Mega sesja pracy głębokiej z Radkiem! Wziąłem udział w sesji i muszę przyznać – to była petarda! Dzięki temu, że inni patrzyli mi na ręce, maksymalnie się skupiłem i zrobiłem dużo więcej w krótszym czasie. Blok czasowy wymusił pełne skupienie, a wymiana spostrzeżeń na koniec dodała jeszcze więcej wartości.',
    t5_name: 'Uczestnik bloków', t5_role: 'Członek MasterZone',
    t5_content: 'Tak naprawdę, dla mnie, te bloki Radka to połączenie przyjemnego z pożytecznym. W ciągu godziny jest miejsce na chwilę rozmowy, zobaczenie znajomych (lub nie) \'pysków\' i zrobienie czegoś dla siebie ważnego. Każdy we własnym zakresie. Więc śmiało, można wbijać - przetestowałem, jest bezpiecznie, jest w porządku i jest efektywnie!',
  },
  transformation: {
    headline: 'Jak Wygląda Zmiana w MasterZone',
    subtitle: 'Nie uczymy Cię produktywności z książek. Dajemy Ci środowisko, w którym produktywność przychodzi sama — bo pracujesz z ludźmi, nie sam.',
    step1: 'Dołączasz i dostajesz onboarding 1:1 — od razu wiesz jak wszystko działa. Żadnego chaosu na start.',
    step2: 'Włączasz się na pierwszy blok pracy. Widzisz ludzi przy komputerach. Twój mózg mówi: \'ok, pracujemy\'. Body doubling w akcji.',
    step3: 'W piątek planujesz tydzień z grupą. Mówisz na głos co chcesz zrobić. Nagle masz plan — i ludzi, którzy zapytają czy go dowieźliście.',
    step4: 'Po tygodniu zauważasz: kończysz zadania, nie odkładasz na jutro, weekendy są wolne od poczucia winy.',
    step5: 'Po miesiącu to Twój nowy tryb pracy. Nie wyobrażasz sobie wrócić do samotnego siedzenia w domu bez nikogo.',
    closingText: 'To nie magia. To body doubling + społeczność + struktura. Trzy rzeczy, których Twój mózg potrzebuje, żeby się skupić — i których nie dostajesz pracując sam.',
  },
  pricing: {
    sectionTitle: 'Prosty, Przejrzysty Cennik',
    sectionSubtitle: 'Wszystko w jednej cenie — bez ukrytych kosztów, bez umów',
    price: '97 PLN',
    planName: 'MasterZone Community',
    guarantee: '97 PLN/miesiąc. Bez umów. Anulujesz kiedy chcesz. 30-dniowa gwarancja zwrotu — jeśli nie zrobisz więcej w 90 min, oddajemy pieniądze.',
  },
  faq: {
    sectionTitle: 'Najczęściej Zadawane Pytania',
    q1: '97 PLN/miesiąc — czy to nie za dużo?',
    a1: 'To mniej niż 5 kaw w kawiarni, gdzie idziesz żeby \'mieć ludzi obok\'. Albo mniej niż 1 godzina z coachem produktywności. W MasterZone dostajesz codzienne wsparcie, 20+ bloków pracy na żywo i społeczność. Większość członków mówi, że to najlepsza inwestycja w ich produktywność.',
    q2: 'Próbowałem już wszystkiego — Pomodoro, aplikacje, kursy. Nic nie działa.',
    a2: 'Bo te narzędzia wymagają od Ciebie dyscypliny, której brakuje. MasterZone działa inaczej — bazuje na body doubling, czyli obecności innych ludzi. Nie musisz się zmuszać. Logujesz się, widzisz ludzi przy pracy, i Twój mózg automatycznie przełącza się w tryb skupienia. To biologia, nie silna wola.',
    q3: 'Nie chcę włączać kamery. Czy muszę?',
    a3: 'Kamera jest rekomendowana — bo właśnie to \'bycie widzianym\' uruchamia efekt body doubling. Ale nie musisz mówić, prezentować się ani wyglądać idealnie. Większość osób pracuje w dresie z kubkiem kawy. Chodzi o obecność, nie o występ.',
    q4: 'Jak często odbywają się bloki pracy?',
    a4: 'Bloki odbywają się codziennie od poniedziałku do piątku, 3-4 razy dziennie o stałych godzinach. Wybierasz te, które pasują do Twojego harmonogramu. Nie musisz być na wszystkich — dołączasz wtedy, gdy potrzebujesz.',
    q5: 'Mam ADHD / cechy ADHD — czy to dla mnie?',
    a5: 'Zdecydowanie tak. Body doubling to jedna z najbardziej polecanych technik przez terapeutów ADHD. Obecność innych ludzi pomaga Twojemu mózgowi w regulacji uwagi. Wielu naszych członków ma ADHD i mówi, że MasterZone to jedyna metoda, która działa na dłużej niż tydzień.',
    q6: 'Co jeśli nie mam czasu na kolejny program?',
    a6: 'MasterZone nie dodaje pracy — odejmuje chaos. Zamiast walczyć z prokrastynacją sam, dostajesz środowisko, które trzyma Cię w skupieniu. Większość członków mówi, że w 90 minut na bloku robią więcej niż normalnie w 4 godziny.',
    q7: 'Czy mogę zrezygnować w każdej chwili?',
    a7: 'Tak. Bez umów, bez okresu wypowiedzenia. Anulujesz kiedy chcesz. Ale 92% członków zostaje — bo wreszcie mają środowisko, w którym produktywność przychodzi naturalnie.',
    q8: 'Jak wygląda pierwszy tydzień?',
    a8: 'Po dołączeniu dostajesz onboarding 1:1. Następnie dołączasz do pierwszego bloku pracy i sesji planowania. Większość osób mówi, że różnicę czują już pierwszego dnia — bo sam fakt, że ktoś obok pracuje, zmienia wszystko.',
  },
  cta: {
    headline: 'Ile jeszcze poniedziałków zaczniesz bez planu?',
    subheadline: 'Dołącz do MasterZone i zacznij pracować w skupieniu — z ludźmi, którzy rozumieją Twoją codzienność.',
    buttonText: 'Dołącz do MasterZone',
    buttonUrl: 'https://www.skool.com/masterzone',
  },
  joinsection: {
    headline: 'Dołącz do MasterZone i przestań pracować sam',
    subtitle: 'Codziennie pracujesz z ludźmi, którzy rozumieją Twoją codzienność. Planujesz raz w tygodniu z jasnością. I wreszcie kończysz to, co zaczynasz — bez zmuszania się.',
    block1_title: 'Body doubling — Twoje wirtualne biuro',
    block1_description: 'Zamiast pustego mieszkania — codziennie pracujesz z innymi na żywo. Kamera włączona, muzyka w tle, każdy robi swoje. Twój mózg przełącza się w tryb skupienia automatycznie — bo widzi, że inni pracują.',
    block2_title: '97 PLN/miesiąc — bez umów, pełna kontrola',
    block2_description: 'Nie ma haczyków ani umów. Zostajesz tak długo, jak to działa. Anulujesz kiedy chcesz. To mniej niż coworking, a dostajesz codzienne wsparcie, planowanie i społeczność.',
    contrastText: 'Jutro możesz znów siedzieć sam, scrollować telefon i obiecywać sobie że \'od poniedziałku się ogarnę\'. Albo możesz dołączyć do ludzi, którzy już to zrobili.',
  },
};
